provider:
  name: openfaas

functions:
  cows:
    lang: node18
    handler: ./cows
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/cows:${TAG:-latest}

  alpine:
    lang: dockerfile
    handler: ./alpine
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/alpine:${TAG:-latest}

  curl:
    lang: dockerfile
    handler: ./curl
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/curl:${TAG:-latest}

  shasum:
    lang: dockerfile
    handler: ./shasum
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/shasum:${TAG:-latest}

  hey:
    lang: dockerfile
    handler: ./hey
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/hey:${TAG:-latest}

  nmap:
    lang: dockerfile
    handler: ./nmap
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/nmap:${TAG:-latest}

  nslookup:
    lang: dockerfile
    handler: ./nslookup
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/nslookup:${TAG:-latest}

  nodeinfo:
    lang: node18
    handler: ./nodeinfo
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/nodeinfo:${TAG:-latest}

  figlet:
    lang: dockerfile
    handler: ./figlet
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/figlet:${TAG:-latest}

  imagemagick:
    lang: dockerfile
    handler: ./imagemagick
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/imagemagick:${TAG:-latest}

  ffmpeg:
    lang: dockerfile
    handler: ./ffmpeg
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/ffmpeg:${TAG:-latest}

  youtube-dl:
    lang: dockerfile
    handler: ./youtube-dl
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/youtube-dl:${TAG:-latest}
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
      exec_timeout: 5m
    labels:
      com.openfaas.ui.ext: "mp4"

  sleep:
    lang: golang-middleware
    handler: ./sleep
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/sleep:${TAG:-latest}
    environment:
      sleep_duration: 2s

  haveibeenpwned:
    lang: go
    handler: ./haveibeenpwned
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/haveibeenpwned:${TAG:-latest}

  printer:
    lang: golang-middleware
    handler: ./printer
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/printer:${TAG:-latest}

  certinfo:
    lang: go
    handler: ./certinfo
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/certinfo-fn:${TAG:-latest}

  external-ip:
    lang: golang-middleware
    handler: ./external-ip
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/external-ip-fn:${TAG:-latest}

  markdown:
    lang: golang-middleware
    handler: ./markdown
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/markdown-fn:${TAG:-latest}

  nvidia-smi:
    lang: dockerfile
    handler: ./nvidia-smi
    image: ${SERVER:-ghcr.io}/${OWNER:-openfaas}/nvidia-smi:${TAG:-latest}

configuration:
  templates:
    - name: golang-middleware
      source: https://github.com/openfaas/golang-http-template
