name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    permissions:
      packages: write
      checks: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Docker Login
        run: > 
          echo ${{ secrets.GITHUB_TOKEN }} | 
          docker login ghcr.io --username 
          ${{ env.REPO_OWNER  }} 
          --password-stdin
      - name: Publish multi-arch functions
        run: >
          OWNER="${{ env.REPO_OWNER  }}" 
          TAG="latest"
          SERVER="ghcr.io"
          faas-cli publish
          --extra-tag ${{ github.sha }}
          --build-arg GO111MODULE=on
          --platforms linux/arm64,linux/amd64

      - name: Publish amd64-only functions
        run: >
          OWNER="${{ env.REPO_OWNER  }}" 
          TAG="latest"
          SERVER="ghcr.io"
          faas-cli publish
          --extra-tag ${{ github.sha }}
          --platforms linux/amd64
          -f stack-amd64.yml
